### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by rkrishnan8594** [rkrishnan8594/MovieGame#2]
### Design
- [x] Complete 'Sign In'
- [ ] Logo
- [x] Sign Up
- [ ] Main Feed
- [ ] Active Game
- [ ] User Profile
- [ ] Splash

### Authentication
- [ ] Enable Facebook sign in
- [ ] Error messages for unsuccessful authentication/registration

### Testing
- [ ] Set up native device testing
- [ ] Include Karma and/or Jasmine frameworks

### Misc
- [x] Split SCSS up into different files
- [ ] Add README
